name: Build test build
on: [push]
jobs:
  Build_Deb:
    runs-on: ubuntu-22.04
    steps:
      - name: Sync APT
        run: sudo apt update
      - name: Install python and tools
        run: sudo apt install python3 python3-pip debhelper-compat make python3-gi python3-dbus python3-tk python3-pil python3-pil.imagetk libgtk-3-0 gir1.2-ayatanaappindicator3-0.1 build-essential libbluetooth-dev
      - name: Checkout
        uses: actions/checkout@v3
      - name: Change in-app version
        run: bash -c 'echo "VERSION = \"$(git rev-parse HEAD)\"" > src/version_info.py'
      - name: Try to build
        run: dpkg-buildpackage -b
      - name: Move result file to current dir
        run: mv ../openfreebuds_*_all.deb openfreebuds_test.deb
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: Debian package
          path: openfreebuds_test.deb

